spring.application.name=api
server.port=${SERVER_PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://dockerbdmonedas:5432/monedas

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresqlcalendario-laboral-db.cx4cy4u4460o.us-east-2.rds.amazonaws.com:5432/calendariolaboral}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Cripto-2026}

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

express.api.base-url=${EXPRESS_API_BASE_URL:http://localhost:3000}
express.api.usuario=${EXPRESS_API_USUARIO:frayosorio}
express.api.clave=${EXPRESS_API_CLAVE:123}
